### ISSUE TITLE
Selecting a row in the events table should select the corresponding state in the time graph

### ISSUE THREAD

**Issue by mirsky-work** [theia-ide/theia-trace-extension#111]
- The time graph's X-axis position should be scrolled to the timestamp of the selected row.
- The time graph's Y-axis should be scrolled to the correct row that contains the corresponding state (would be nice to highlight it).
- The zoom-level of the graph shouldn't be affected.

**Comment by mirsky-work** [comment]
Fixed by #207

**Comment by muddana-satish** [comment]
@mirsky-work It's not a fully implemented feature with #207 . I think this should still be open.
