### ISSUE TITLE
Resources Status, Disk I/O View takes longer to load

### ISSUE THREAD

**Issue by ankusht-work** [theia-ide/theia-trace-extension#112]
Steps to reproduce:
1) Open and close the resources status view multiple times.
2) You will notice that the subsequent opening of any of the views will take longer to load.

Environment: Tested on a Linux machine with no GPU

Note: It works OK on a machine, with an Intel UHD built-in GPU. 
Also, this could be related to issue  #[https://github.com/theia-ide/timeline-chart/issues/7].

**Comment by MatthewKhouzam** [comment]
To be clear, you mean your Linux machine has no 3d Hardware acceleration.

Does this reproduce the issue in windows? https://www.lifewire.com/hardware-acceleration-in-chrome-4125122

**Comment by ankusht-work** [comment]
> To be clear, you mean your Linux machine has no 3d Hardware acceleration.
> 
> Does this reproduce the issue in windows? https://www.lifewire.com/hardware-acceleration-in-chrome-4125122

The link you shared suggests disabling hardware acceleration. If you disable the hardware acceleration then none of the components that use webGL will load. Error: "WebGL unsupported in this browser". 
Hence I am not sure this is related.

**Comment by MatthewKhouzam** [comment]
Thanks, I was wondering... In Linux, it works, but I think it ignored the flag. ;)

**Comment by ebugden** [comment]
I tried reproducing this in the most recent version of the Trace Viewer demo and views didn't take noticeably longer to load. @MatthewKhouzam @mirsky-work Can I close this?

**Comment by mirsky-work** [comment]
Wasn't able to reproduce on a similar environment that @ankusht-work used either. Closing, thanks for the reminder @ebugden!
