### ISSUE TITLE
Clarify behavior of events table

### ISSUE THREAD

**Issue by mad-season** [theia-ide/theia-trace-extension#126]
We need to clarify the behavior of the events table in the following scenarios:

- Searching / filtering a column. Since there will always be only a limited number of rows in memory, do we filter/search only in-memory rows? Or do we send a server request to fetch all rows that match a search/filter query? If we fetch from the server, what if the number of rows fetched is much higher than our in-memory limits? Does the front-end then request batches of matched rows? What (if any) API's need to be added to the trace-server to support all this kung-fu?
- Jumping to a row due to, say, state selection in the timechart. If the selected row is not included in the rows in memory, do we fetch the row +- a range from the server? IIrc a server-side API is already being developed as I write. @MatthewKhouzam please confirm.

Are there other scenarios I've missed that should be considered? The more we can come up with, the better the final design of the table widget will be.

@bhufmann @MatthewKhouzam @tahini please weigh in.

**Comment by mirsky-work** [comment]
I believe the decision that was made is to fetch search results from the server (#396). Closing.
