### ISSUE TITLE
Implement the share button

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/theia-trace-extension#142]
Right now the trace explorer has button beside each experiment to create a URL that can be shared with users for sharing of traces and trace analysis session. The functionality to share traces and trace session is currently not implemented. Only a dialog with a URL is opened. See picture below.

![image](https://user-images.githubusercontent.com/413424/95242480-3ac3a800-07dd-11eb-8906-d503061ed567.png)

This issues is to track the feature implementation for this feature.

**Comment by bhufmann** [comment]
#143 will first remove the button until this issue is implemented.

**Comment by ebugden** [comment]
Related issue: #20

**Comment by ebugden** [comment]
Going to close this since we don't know if sharing will be implemented using this button in the future.
