### ISSUE TITLE
Disappearing timegraph states

### ISSUE THREAD

**Issue by PatrickTasse** [theia-ide/theia-trace-extension#145]
In the timegraph, short states appear and disappear depending on the zoom level.
It could be an issue with the handling of gaps in between the sampling of states returned by the server.

**Comment by tahini** [comment]
I might be fixing it incidentally with a huge patch to align with newest TSP, as I noticed this and had to change a few things here and there. If you want a quick fix, look at the tsp-data-provider.ts, line 121, the conditionn  nextState.value < 0 should be changed with something looking at start/end times of both states.

**Comment by tahini** [comment]
PR https://github.com/theia-ide/theia-trace-extension/pull/147 may fix it as a side effect. Could you see if it does? But it requires a few PRs everywhere else

**Comment by PatrickTasse** [comment]
This issue appears to be fixed.
