### ISSUE TITLE
Gaps should have default style

### ISSUE THREAD

**Issue by PatrickTasse** [theia-ide/theia-trace-extension#148]
The gap states (that are inferred to exist between the real states returned in the row model) are all drawn in a generic color.
In Eclipse Trace Compass, they are drawn using the style of their entry (that was returned in the tree model).

However, although right now this style is not used for any other purpose in time graphs (it is used in XY charts), the color of this style should probably refer to the tree section of the time graph (e.g. the tree text color?), and perhaps a different parameter (ie. defaultStateStyle) could be added to the protocol and/or model for this purpose. This could maybe be added to the TimeGraphRow model (state endpoint) instead of the TreeDataModel (tree endpoint).

**Comment by tahini** [comment]
A gap will typically be 1 pixel wide, so it's hard to know whether it's a gap or a real state, unless it's really obvious. In Trace Compass, we add a dot above the state to say that other states are included in the pixel. Here, the generic CACACA color does look generic enough to speak of a generic state.

Using the state color as in Trace Compass shows glitches all along the way as we zoom (see screencast here). The color keeps changing, so I'm not sure that's more desirable, especially that we don't know there's any other state there.

![default-gap-state](https://user-images.githubusercontent.com/4398897/96266697-f088b680-0f94-11eb-9023-01c254f4941f.gif)

Maybe @ebugden has some clever idea to display the fact that there are various states under a single pixel? I guess implementing rounded time queries would be a good start as there would be no arbitrary glitches in state sampling, but still we need to know there's a gap.

**Comment by PatrickTasse** [comment]
In Trace Compass, if the only state drawn at a pixel is a gap (e.g. between two long null states), we won't draw the dot (because there's only one state), even though that gap may represent one or more states. This is probably the only case where we draw the gap's color (if there is a real state intersecting that pixel, either left, right, or both, that should be the pixel's color).

In theia-trace-extension, we don't draw any dots at all anyways, right?

But looking at this screencast, it appears that the default style for SOFT_IRQ rows should be yellow, not blue, as this is a better guess for the real states on those rows? Where is the blue coming from?

**Comment by tahini** [comment]
state colors for resources view are completely wrong. They are to be ignored for now. They should come from the server eventually and our default states should make no assumption on state height or color or potential values, etc, just be a round-robin of colors.
