### ISSUE TITLE
Add “Open Trace” button to trace extension sidebar

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#160]
Adding an “Open Trace” button to trace extension sidebar keeps this operation intuitive by imitating how a folder is opened in VS Code.

* This button and text is only visible when no traces are open.
* If all currently open traces are closed, this text and button reappears.

![open-trace-button2](https://user-images.githubusercontent.com/28311615/99849043-d4a2a280-2b48-11eb-8bb7-6a07f371c44f.PNG)

Text and button style:
![vscode-open-folder-button](https://user-images.githubusercontent.com/28311615/95926042-4852d200-0d89-11eb-8e18-5adc3ae50395.PNG)

**Comment by muddana-satish** [comment]
@ebugden @tahini @bhufmann What should the file explorer contents look like after the trace is loaded using 'Open Trace' option? 

I can think of three possible solutions.

1. Show only the newly loaded trace.
2. Show  parent folder of the newly loaded trace and all the contents of the parent.
3. Do not modify anything in the file explorer. (show whatever is shown before loading the trace)

**Comment by ebugden** [comment]
This is a good question. For now, to keep things simple, I suggest option **1. Just the newly loaded trace (root folder and contents)**. As if you were opening a new project in the IDE.

(This will probably change in the final tool. I think the right answer for the final tool depends on what the expected final workflow of the tool will be. For example, are users going to be frequently wanting to make links between the trace and source code or will most users only ever be looking at the trace tab? These are questions that we don't currently have answers for so I would just do the simple thing for now.)

**Comment by ebugden** [comment]
@tahini @bhufmann Would users commonly want to look at the raw trace files, metadata? If yes, what information would they be looking for?

**Comment by mirsky-work** [comment]
I would argue that opening a trace through a button in the Trace Explorer shouldn't implicitly affect the File Explorer. We can consider adding an option to sync the File Explorer to a selected experiment's location, but I think it should be explicit. For the MVP, I think we can go with option 3.

**Comment by bhufmann** [comment]
In VsCode and Theia, the sync. of editors with the file explorer is controlled by the setting: "explorer.autoReveal". This works fine with source code files. It currently doesn't work with open traces. To support the sync. between the file explorer and the open traces I think we should piggyback on the "explorer.autoReveal" procedure.

@ebugden  I think, users would expect that to the location is revealed, where the trace(s) are. 
@mirsky-work  I'm ok with option 3.
