### ISSUE TITLE
Cursor is a cross when graph selection is possible 

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#162]
The cursor being a cross when selection is possible supports intuitive understanding by following UI standards set by other tools (ex. Grafana, Google Slides):

![cursor-cross](https://user-images.githubusercontent.com/28311615/95929485-18f49300-0d92-11eb-81c8-e4f2ef89c7de.PNG)

![grafana-cross-cursor](https://user-images.githubusercontent.com/28311615/95929428-f793a700-0d91-11eb-9590-676d1dbf4774.gif)

**Comment by bhufmann** [comment]
As stated her https://github.com/theia-ide/theia-trace-extension/pull/697#pullrequestreview-907559125, the change to crosshair is only done when clicking and holding the left mouse button. Closing this issue.
