### ISSUE TITLE
Cursor is an arrow cross when moving is possible 

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#163]
The cursor becoming an arrow cross when the object underneath can be moved supports intuitive understanding by following UI standards set by other tools (ex. Grafana, Google Slides):

![cursor-arrow-cross](https://user-images.githubusercontent.com/28311615/95929586-5e18c500-0d92-11eb-9fff-624e85b8d541.PNG)

![grafana-arrow-cross-cursor](https://user-images.githubusercontent.com/28311615/95929770-c2d41f80-0d92-11eb-87d2-119627a940e5.gif)

**Comment by Ab-rahe** [comment]
I will start working on that issue.
Abdellah
