### ISSUE TITLE
Support segment statistics in Theia

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#17]
- [ ] Provide the data through a data provider in Trace Compass

![SegmentStatistics](https://user-images.githubusercontent.com/4398897/82827472-1d6ced80-9e7d-11ea-83f9-61b2dc386230.png)

**Comment by tahini** [comment]
@bhufmann you assigned yourself this task. What is the status? I'm planning to start work on https://github.com/theia-ide/trace-server-protocol/issues/35 and statistics are a good use case of data to format, so I could help with this along the way.

**Comment by bhufmann** [comment]
@tahini not much news. I haven't had a chance to work on it. It's in our backlog for this year. Hopefully even first half of the year. If you could help it would speed things up. You could implement first the front-end and show the stats tree as strings which are currently formatted in the statistics data provider. After that you could tackle the formatting of data and update the UI. Just a suggestion.

**Comment by bhufmann** [comment]
This feature was implemented by #598 and made the implementation visible by #607.
