### ISSUE TITLE
Weird state look when making a time graph view bigger

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#175]
When resizing a time graph component to make it bigger, the new rows that are shown have some extra states or fillers or something. See the following screenshot 

![timeGraphResized](https://user-images.githubusercontent.com/4398897/97354288-8d880100-186b-11eb-8c52-542088156222.png)

A quick bisect shows the problem arrived at commit e421d81 , but it may be due to updates in the timeline-chart that happened

**Comment by tahini** [comment]
@abhinava-ericsson  @muddana-satish  maybe you'll have an idea?

**Comment by muddana-satish** [comment]
I will have a look into it. Thanks for reporting.

**Comment by muddana-satish** [comment]
@tahini Do you have a trace where I can reproduce this issue consistently. I tried with several traces and none of them have this issue.

**Comment by tahini** [comment]
I can reproduce consistently here with any trace... on linux/firefox. It's when resizing the view from the bottom right handle.

Here's a screencast of it

![timeGraphResize](https://user-images.githubusercontent.com/4398897/97374253-48c19180-188e-11eb-959b-58ed6edc6e52.gif)

**Comment by bhufmann** [comment]
@tahini I've uploaded a patch in the timeline-chart https://github.com/theia-ide/timeline-chart/pull/100#issue-556886419 repo that fixes issue #209. Could you please verify that this pull request also fixes this issue that you've reported? Thanks Bernd

**Comment by tahini** [comment]
It is fixed, thanks!

**Comment by bhufmann** [comment]
Great, thanks for verifying.
