### ISSUE TITLE
Support tree/table data in Theia

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#18]
Some data providers only provide tree or table data (no time line required). The respective outputs should be displayed properly.

**Comment by ebugden** [comment]
@bhufmann Can this be closed? Does this refer to views like the Events Table?

**Comment by bhufmann** [comment]
> @bhufmann Can this be closed? Does this refer to views like the Events Table?

No, it cannot be closed because it refers to data providers of type DATA_TREE, which is used, for example the Trace Compass function duration statistics.

**Comment by ebugden** [comment]
@bhufmann Is this a duplicate of #144? Can it be closed?

**Comment by bhufmann** [comment]
yes, it's a duplicate and can be closed
