### ISSUE TITLE
Long texts not visible in trace explorer

### ISSUE THREAD

**Issue by muddana-satish** [theia-ide/theia-trace-extension#181]
![image](https://user-images.githubusercontent.com/70230232/98312272-3201f580-1f86-11eb-8e71-e31d7312c29d.png)

We should support a tooltip or a horizontal scrollbar.

**Comment by ebugden** [comment]
Fixed roughly by PR #229. Now users can expand the side panel to read text. Probably not the final solution, but fixed for now.

https://user-images.githubusercontent.com/28311615/112354469-1b450c80-8ca3-11eb-83b6-ed0bc1767833.mp4
