### ISSUE TITLE
Display Invalid Trace message

### ISSUE THREAD

**Issue by muddana-satish** [theia-ide/theia-trace-extension#187]
Trace Viewer should show an invalid trace message for all invalid traces.

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/70230232/100123629-969acc80-2e2f-11eb-8644-5203738a257c.png">

Currently, it's just empty.

**Comment by ebugden** [comment]
I don't understand the issue description. When a file that is not a recognized trace format is opened as a trace, the Trace Explorer side panel is empty? 

Could you add more precision to the issue description and/or add a GIF that shows the issue?

**Comment by muddana-satish** [comment]
>  When a file that is not a recognized trace format is opened as a trace, the Trace Explorer side panel is empty?

Yes, this is what I meant. We should display an error message to the user.  Attached a gif. I opened an xml file(invalid trace). The user should be shown with an error message. Right now, we do not show anything.

Any thoughts? 

![Kapture 2020-12-02 at 18 21 43](https://user-images.githubusercontent.com/70230232/100955583-a10e3380-34cb-11eb-8b95-93ae7a3a87f3.gif)

**Comment by bhufmann** [comment]
I agree that the there should be a feedback to the user about that. 

For an trace type that is unknown by the trace server, it return status 501 (NOT_IMPLEMENTED). I realized when trying it, that there is an uncaught exception created because the tsp-typescript-client can't handle the error case:
```
Uncaught SyntaxError: Unexpected token T in JSON at position 0
message:'Unexpected token T in JSON at position 0'
stack:'SyntaxError: Unexpected token T in JSON at position 0'
```

Looking briefly at the tsp-typescript-client other commands have similar issues when an error code is return.

**Comment by ebugden** [comment]
Is it possible for a user to try and open any file type as a trace? I'm wondering if it's worth mentioning in the warning message that the file could not even be a trace file (ex. table.csv, randomtext.txt, executable.bin). Or do typical users know enough about what a trace is that that's an extreme corner case?
