### ISSUE TITLE
Add intuitive way to open additional traces

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#193]
Currently, there is no intuitive way to open additional traces if a trace is already open. Without this, users could become frustrated early in their user experience or assume that you can only open one trace at a time. 

Initially, this use case was going to be covered by adding an "Open Trace" option to the File menu #159, but the VS Code extensions API does not allow contributions to the main menu: 
* VS Code menu contribution points [documentation](https://code.visualstudio.com/api/references/contribution-points#contributes.menus)
* [Comment](https://github.com/theia-ide/theia-trace-extension/issues/159#issuecomment-733749083) on Add “Open Trace” option to File menu #159 

The other currently planned options for opening a trace do not cover this use case:
* The "Open Trace" button #160 just covers the case where no traces are open.
* The current alternatives (Right-click in the file explorer, CTRL+SHIFT+P + "Open Trace") would not be the user's first reflex.

## Proposed solution
Keep the "Open Trace" button (from PR #186) in the side panel menu even after opening the first trace (ex. under the opened traces)

![image](https://user-images.githubusercontent.com/28311615/135626575-5a0ea6cf-d1d9-41b3-b39e-d4ef6a29bed7.png)

**Comment by bhufmann** [comment]
I would argue that VsCode/Theia users are familiar with the command interface using CTRL+SHIFT+P / F1. AFAIK the idea of the command interface in VsCode was to avoid cluttering the UI. 

Maybe adding a button or menu in the trace explorer is a way forward and to to help new users.

**Comment by ebugden** [comment]
> I would argue that VsCode/Theia users are familiar with the command interface using CTRL+SHIFT+P / F1. AFAIK the idea of the command interface in VsCode was to avoid cluttering the UI.

I think that depends on the user's experience and learning path (ex. I used VS Code for ~3 years without ever getting into using commands consistently. I personally never felt like the feature was intentionally tutorialized as part of the core tool use.) 

Opening files is a core operation and it seems very UI conservative to mainly use commands.

---

> Maybe adding a button or menu in the trace explorer is a way forward and to to help new users.

# Button
Off the top of my head, maybe a clickable icon that appears on mouseover of the trace files section like in the VS Code file explorer:
![image](https://user-images.githubusercontent.com/28311615/101390149-61ab6280-3890-11eb-9ef5-342aed00b4e3.png)

**Quick icon ideas:**
![image](https://user-images.githubusercontent.com/28311615/101392516-da5fee00-3893-11eb-81c9-7b4091c40a2d.png)

1. Plus sign: It's a little vague: "Add what?". You'd need the tooltip text to know what it means without testing it. 
2. File: I think the file could be a good option. Possibly vague about what the action would be: "Do what with a file?" 
3. Folder: See 2. for flaws. Perfetto uses just a folder: 
![image](https://user-images.githubusercontent.com/28311615/101393896-c9b07780-3895-11eb-8cfc-1cc71e8c657f.png)
4. File with plus: More explicit action: "You're adding a file", but VS Code already uses these icons in the explorer to indicate adding a new empty file or folder. So should probably avoid using these for a slightly different action.
5. Folder with plus: See 4. for flaws.
6. Me trying to imitate VS Code style icons. Does Theia or VS Code have icons for opening existing files?  

Could have an icon that changes when you mouse over it to suggest the action. Would that feel out of place in the tool's visual style?
![image](https://user-images.githubusercontent.com/28311615/101392577-ecda2780-3893-11eb-9700-01c9a8a40803.png)

# Menu
"Right-click on Trace Explorer menu --> Open Trace" was another quick idea, but I'm trying to avoid dumping features in right-click menus.
![image](https://user-images.githubusercontent.com/28311615/101393392-0cbe1b00-3895-11eb-81ea-adbdc31405d8.png)

**Comment by ebugden** [comment]
I keep bumping up against this issue when using the Trace Viewer. #159 is still my favourite solution (and we can always add something else for VS Code when that transfer happens). @ssmagula what do you think?

**Comment by ebugden** [comment]
Keeping button in the Opened Traces widget - Implementation notes

Relevant files below (for code examples). Exploring files to figure out how and where to implement the button.

## trace-explorer-placeholder-widget.tsx
![image](https://user-images.githubusercontent.com/28311615/141325370-5b104ca8-2ea0-4244-9b86-44237a61265a.png)

* render( ) 
  * button --> onClick --> handleOpenTrace 

Does the context menu in the file explorer use the same approach to Open Traces (is the code copied)? Debating whether there's an approach for adding a button that doesn't 

```typescript
    render(): React.ReactNode {
        const { loading } = this.state;
        return <div className='theia-navigator-container' tabIndex={0}>
            <div className='center'>{'You have not yet opened a trace.'}</div>
            <div className='open-workspace-button-container'>
                <button className='theia-button open-workspace-button' title='Select a trace to open'
                    onClick={this.handleOpenTrace} disabled={loading}>
                    {loading && (
                        <i
                            className='fa fa-refresh fa-spin'
                            style={{ marginRight: '5px' }}
                        />
                    )}
                    {loading && <span>Connecting to trace server</span>}
                    {!loading && <span>Open Trace</span>}
                </button>
            </div>
        </div>;
    }
```

## theia-trace-explorer-opened-traces-widget.tsx
![image](https://user-images.githubusercontent.com/28311615/141326314-34999ca2-4b1e-4b7f-88c2-5d01647c7277.png)

The TraceExplorerOpenedTraceWidget contains the ReactOpenTracesWidget, but I don't know why in needed to be separated in two files.

trace-explorer-opened-traces-widget.tsx
```typescript
    render(): React.ReactNode {
        const totalHeight = this.getTotalHeight();
        this._forceUpdateKey = !this._forceUpdateKey;
        const key = Number(this._forceUpdateKey);
        return (
            <>
                <ReactModal isOpen={this._showShareDialog} onRequestClose={this.handleShareModalClose}
                    ariaHideApp={false} className='sharing-modal' overlayClassName='sharing-overlay'>
                    {this.renderSharingModal()}
                </ReactModal>
                <div className='trace-explorer-opened'>
                    <div className='trace-explorer-panel-content'
                        onClick={this.updateOpenedExperiments}>
                        <AutoSizer>
                            {({ width }) =>
                                <List
                                    key={key}
                                    height={totalHeight}
                                    width={width}
                                    rowCount={this.state.openedExperiments.length}
                                    rowHeight={this.getRowHeight}
                                    rowRenderer={this.renderExperimentRow}
                                />}
                        </AutoSizer>
                    </div>
                </div>
            </>
        );
    }
```

**Comment by ebugden** [comment]
@hriday-panchasara and @mirsky-work here are my favourite options for implementing an additional way to open traces. I think any of these would be ok. Thank you for working on this! CC: @ssmagula 

## + Folder icon (appears on hover)
The icon would appear next to "Opened Traces" section on hover (exactly as shown in the video below). If the "+ folder" icon (copied from VS code) is tricky to find, a simple "+" would be ok (since it's right on the "Opened Traces" section this gives context for what you would be adding). 

![image](https://user-images.githubusercontent.com/28311615/144270592-37e76424-bee7-476b-862b-4f22bd64bd94.png)


![image](https://user-images.githubusercontent.com/28311615/144270308-37ed3ab2-2e7c-448a-a7b0-6bcca0b482e6.png)

The icon would appear when you hover on the "Opened Traces" section like this: 

https://user-images.githubusercontent.com/28311615/144270462-0f3b019d-74e6-4f9c-9556-660d64beebf6.mp4

## "Open Trace" button 
Keep the "Open Trace" button (from PR #186) in the side panel menu even after opening the first trace (ex. under the opened traces). This is super obvious and users would immediately understand, but it takes up more space.

![image](https://user-images.githubusercontent.com/28311615/135626575-5a0ea6cf-d1d9-41b3-b39e-d4ef6a29bed7.png)

## + Folder icon (at the top)
This placement is good for now. We should stay open to moving it later if we need that space for a more general icon. Substituting the "+ folder" icon with just a "+" works less well here because there is less context for what you would be adding.   

![image](https://user-images.githubusercontent.com/28311615/144271912-9e017905-8946-47a5-a1df-d17dc28e33a7.png)

**Comment by mirsky-work** [comment]
Thanks for the suggestions @ebugden! Regarding the '+ folder' icon, although in most cases the trace is a CTF folder, we do want to support single-file traces, for example in JSON format, so IMO a general '+' would be a better fit.

**Comment by ebugden** [comment]
> Regarding the '+ folder' icon, although in most cases the trace is a CTF folder, we do want to support single-file traces, for example in JSON format, so IMO a general '+' would be a better fit.

It's true that single files will also be supported, but I don't think the folder icon would be confusing. If anything, I think a user's first reflex would be to assume that a single trace is a single file, but using the folder icon could suggest that this isn't always the case and sometimes a single trace is a folder.

As a reference, Perfetto uses a folder icon to represent "Open trace file":

![image](https://user-images.githubusercontent.com/28311615/101393896-c9b07780-3895-11eb-8cfc-1cc71e8c657f.png)

In the end, I think either are safe options and we can see how the option chosen performs in user tests.

**Comment by hriday-panchasara** [comment]
@mirsky-work @ebugden Here's an initial implementation. Let me know what you think
![Screen Shot 2021-12-01 at 4 57 38 PM](https://user-images.githubusercontent.com/92893187/144327775-dcfd82cf-d129-47ee-9180-5c4594841ccc.png)

https://user-images.githubusercontent.com/92893187/144327795-8c5eabc6-dc2c-4df0-8248-57bd1892402b.mov

**Comment by bhufmann** [comment]
> @mirsky-work @ebugden Here's an initial implementation. Let me know what you think ![Screen Shot 2021-12-01 at 4 57 38 PM](https://user-images.githubusercontent.com/92893187/144327775-dcfd82cf-d129-47ee-9180-5c4594841ccc.png)
> 

I suggest to add a + to the icon. I think it makes clearer what it does. Otherwise it looks good to me.

**Comment by mirsky-work** [comment]
> @mirsky-work @ebugden Here's an initial implementation. Let me know what you think ![Screen Shot 2021-12-01 at 4 57 38 PM](https://user-images.githubusercontent.com/92893187/144327775-dcfd82cf-d129-47ee-9180-5c4594841ccc.png)

I second @bhufmann for a '+' or '+ folder' icon.
Can the button be added to the widget header, like in the File Explorer below?
![Screenshot 2021-12-02 164907](https://user-images.githubusercontent.com/67920463/144515716-99f56f1b-01bf-487f-87da-5403aaef391e.png)
