### ISSUE TITLE
Timeline-chart rows not aligned with tree after vertical zoom

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/theia-trace-extension#210]
Performing zoom operation the browser (CTRL++) will cause timeline-chart rows to be not aligned with the tree on the left side. In the example below see the selected row ("CPU 2 States") in before and after the zoom operation.
**Before zoom:** 
![image](https://user-images.githubusercontent.com/413424/104051165-b276e980-51b5-11eb-956b-193166b629e6.png)

**After zoom**
![image](https://user-images.githubusercontent.com/413424/104051181-bc005180-51b5-11eb-8026-63a1f8abe829.png)

**Comment by MatthewKhouzam** [comment]
Does this still apply? I remember some patches on the tree recently.

**Comment by bhufmann** [comment]
I just tried it and it's not an issue anymore. I'll close this issue.
