### ISSUE TITLE
Should the status bar change color according to the connection status with the server?

### ISSUE THREAD

**Issue by mirsky-work** [theia-ide/theia-trace-extension#214]
The default color of the status bar in Theia is blue. The trace extension changes that default to yellow, to indicate that the trace server is offline (or connection is interrupted):
![statusbar-yellow](https://user-images.githubusercontent.com/67920463/104367325-44e1fa80-54e0-11eb-883c-54a372b5f3e0.png)

And changes back to the default blue when the server is started (or connection restored):
![statusbar-blue](https://user-images.githubusercontent.com/67920463/104367403-5fb46f00-54e0-11eb-8d3d-7fe8e1d6ef2b.png)

When the trace extension is integrated into an IDE, the yellow status bar, unless the user pro-actively started the trace server, might be a visual distraction when the user is performing other activities unrelated to tracing, such as writing code. Moreover, it might conflict with other plugins that also change the status bar's color, e.g., [Debugger in VS Code](https://www.youtube.com/watch?v=BYRoxIYP04M).

The suggestion is to avoid changing the color of the status bar, and instead rely solely on the _start/stop server_ button that changes according to the connection status. Thoughts?

@ebugden, @danieltomasku, @bhufmann

**Comment by bhufmann** [comment]
I agree with your conclusion for the IDE integration case. With current state of the tool I think it's ok to rely on the different buttons to indicate the state of the trace server. This will not or less distract users that are not doing trace analysis but do tasks like coding or debugging. 

In later a stage of the project, I suggest to start the trace server (local case), monitor the trace server connection (local and remote case) and show the trace server status only when users are initiating trace analysis.

**Comment by ebugden** [comment]
Yes, I agree with keeping the bar blue to avoid distracting users who aren't using tracing. 

It makes sense to alert a user using trace analysis if it's not possible to start the server or if it's unresponsive, but I think that's a different issue.

----

As @bhufmann suggested, I created an issue for starting the trace server when a user opens a trace #221. I wasn't sure what tags to use.

**Comment by ebugden** [comment]
I created an issue for this change so I'm going to close this discussion.
