### ISSUE TITLE
Use the same name to describe the trace viewer

### ISSUE THREAD

**Issue by mirsky-work** [theia-ide/theia-trace-extension#217]
The trace viewer/extension is referred to using different names in different contexts, which can be a source of confusion for the users. _Trace Explorer_ and _Trace Viewer_ are used in the screenshot below:

![trace-viewer-settings](https://user-images.githubusercontent.com/67920463/104373580-3b5b9100-54e6-11eb-8bf8-a82bad94dcad.png)

In the _Open With_ context menu it says "Open Trace", but it would make more sense if it would say "Trace Viewer" or "Trace Explorer" (or whatever we'll decide to call it).
![open-trace](https://user-images.githubusercontent.com/67920463/104373588-3dbdeb00-54e6-11eb-86d0-a48ee276c538.png)

**Comment by bhufmann** [comment]
Makes senses. I think the "Trace Viewer" is the application that includes the trace explorer, preferences and chart container. So, I think the command "Open With" -> "Open Trace" should be changed to "Open With" -> "Trace Viewer".

**Comment by ebugden** [comment]
@mirsky-work Thank you for mentioning these issues! These are low-effort changes that have a big impact on polish.

----

I agree with @bhufmann's suggestions to change "Open With" -> "Open Trace" to "Open With" -> "Trace Viewer".

----
My intuition would be to also change "Trace Explorer" to "Trace Viewer" even if this is only a part of the whole trace viewer:
* **It's an unintuitive/unnecessary distinction for the user:** I personally never realized the parallel between "Trace Explorer" and "File Explorer". I thought it was an inconsistency in the tool name inside the tool.
* **"Trace Explorer" arguably isn't complete:** This side menu also allows for exploring analyses

What do you think?

**Comment by danieltomasku** [comment]
- +1 for changing the context menu text from "Open Trace" -> "Trace Viewer" 
- +1 for changing the side panel label from "Trace Explorer" -> "Trace Viewer"
  - A common pattern for VS Code/Theia extensions is to label the side panel the same as the extension name. Since this is the main entrypoint into the extension, it also helps to be consistent with the naming.

**Comment by ssmagula** [comment]
I agree. The identity of the plugin should be consistent throughout the experience. Note that the plugin name is also used in the confirmation message, displayed when a user successfully loads a trace via a context menu (see: https://github.com/theia-ide/theia-trace-extension/pull/208)
- Was: "Trace file loaded successfully <br> To see available analyses, view the Trace Explorer tab"
- Now: "Trace loaded successfully <br> For available analyses, see Trace Viewer"

**Comment by ebugden** [comment]
To summarize, the extension should be referred to as "Trace Viewer" everywhere in the MVP. 

All of the green underlined text in images below should be replaced with "Trace Viewer".
![image](https://user-images.githubusercontent.com/28311615/104977811-740bd680-59ce-11eb-8dd3-383c9ceec669.png)
![image](https://user-images.githubusercontent.com/28311615/104977848-8d148780-59ce-11eb-80e2-d55e1d1e9887.png)
![image](https://user-images.githubusercontent.com/28311615/104977910-acabb000-59ce-11eb-8bd9-e6d11038ef4d.png)
![image](https://user-images.githubusercontent.com/28311615/104977940-c6e58e00-59ce-11eb-861e-181e84d938ef.png)
