### ISSUE TITLE
Start trace server when user opens a trace 

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#221]
Starting the trace server at the moment a user opens a first trace avoids running the server for no reason. At the moment, the server is started when the IDE is opened regardless of if it is being used.

**Comment by bhufmann** [comment]
@ebugden the current implementation is that the trace server is started when the user presses the "Start trace server" button in the status bar. It's not started when the IDE is opened.

This topic is also discussed in https://github.com/theia-ide/theia-trace-extension/issues/53#issuecomment-777597632.

**Comment by ebugden** [comment]
Ah ok! [#53 (comment)](https://github.com/theia-ide/theia-trace-extension/issues/53#issuecomment-777597632) sounds good. 

(I think I created this because in the Gitpod demo the server is running at startup, but I guess that's because of a script that starts the server.)

**Comment by bhufmann** [comment]
> Ah ok! [#53 (comment)](https://github.com/theia-ide/theia-trace-extension/issues/53#issuecomment-777597632) sounds good.
> 
> (I think I created this because in the Gitpod demo the server is running at startup, but I guess that's because of a script that starts the server.)

@ebugden in GitPod the trace server is started from the GitPod setup configured through the file .gitpod.yml.
