### ISSUE TITLE
Keep status bar blue when trace server is not running

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#222]
The status bar should be blue even when the trace server is not running to avoid distracting users who are not using the tracing features. See #214 for more detailed discussion of this change.

The bar should remain blue like this: 
![image](https://user-images.githubusercontent.com/28311615/104753091-84e5ef00-5725-11eb-933b-4b8a2aacf94c.png)

Currently, the status bar is yellow:
![image](https://user-images.githubusercontent.com/67920463/104367325-44e1fa80-54e0-11eb-883c-54a372b5f3e0.png)

**Comment by muddana-satish** [comment]
I understand the purpose of this issue. So, if we do not notify the status of the server to the user, then what's the purpose of #224 ? Do we need to keep pinging the server to know it's status?

**Comment by ebugden** [comment]
Nothing changes in the current behaviour of the status bar. It will still have two states: online and offline, which display different text/actions. 

The only change is that in both of these states the bar will be the same blue colour.

**Comment by mirsky-work** [comment]
@ebugden, is it a duplicate of #214 and can be closed now?

**Comment by ebugden** [comment]
@mirsky-work Good point, I'll close this.

Going forward, when a "Discussion issue" becomes an "Issue issue" could we change the question (ex. Should the status bar change color?) to a statement (ex. Keep status bar blue) defining the solution that was decided? Otherwise, it's unclear whether the discussion is ongoing.
