### ISSUE TITLE
Change file explorer context menu text to "Open With" -> "Trace Viewer"

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#223]
The options in the "Open With" menu should be a noun (ex. Code Editor, Trace Viewer) rather than an action (ex. Open Trace). Issue first mentioned in #217. 

![image](https://user-images.githubusercontent.com/67920463/104373588-3dbdeb00-54e6-11eb-86d0-a48ee276c538.png)

**Comment by bhufmann** [comment]
@ebugden, @mirsky-work this one is a duplicate to #217.

**Comment by ebugden** [comment]
Duplicate of one step in #217. Already resolved.
