### ISSUE TITLE
Change title bar colour on mouse over

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#240]
The entire title bar should change colour when the cursor is over it. This shows the user that they can click-drag on any part of the title bar to move the panel. 

![image](https://user-images.githubusercontent.com/28311615/95929770-c2d41f80-0d92-11eb-87d2-119627a940e5.gif)

Related: #239

CC: @ssmagula

**Comment by IbrahimFradj** [comment]
I'll be working on it
