### ISSUE TITLE
Starting trace server: wrong message when port is in use

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#250]
When there is another application running on port 8080 and we click on the "Start trace server" button, the server fails to load with the following message: Failed to start the trace server: no such file or directory. Please make sure that the path is correct in Trace Viewer settings and retry

It should say something along the lines of "cannot bind to port 8080. Is another application running on it?"

**Comment by ebugden** [comment]
@ankusht-work Is this issue still relevant now considering #298?

**Comment by mirsky-work** [comment]
Fixed by #298. An appropriate toast messages is now displayed.
