### ISSUE TITLE
Double clicking a trace in the trace explorer opens the trace.

### ISSUE THREAD

**Issue by muddana-satish** [theia-ide/theia-trace-extension#279]
can we show the trace tab by double clicking on the Opened Traces list entry? Can be implemented in a separate patch.

_Originally posted by @mirsky-work in https://github.com/theia-ide/theia-trace-extension/issues/248#issuecomment-781502460_

**Comment by mirsky-work** [comment]
Some other suggestions that came up in #248:
Open Trace -> Reopen Trace
Delete Trace -> Remove Trace

@ebugden, @ssmagula, any thoughts?

**Comment by ebugden** [comment]
Put my thoughts in #277 ([comment](https://github.com/theia-ide/theia-trace-extension/issues/277#issuecomment-785265558)).

**Comment by muddana-satish** [comment]
> edit: duplicates #277. Perhaps we can edit this issue to be only about opening a tab by double clicking.

Oops! I didn't realize it. Modified the title of the issue.

**Comment by ebugden** [comment]
I like this idea. I didn't realize you couldn't already click on a trace to open it.
