### ISSUE TITLE
Unified cursor for time-based charts

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#288]
Right now, all time-based charts share one axis and panels (time-based or not) can be placed in any order. Association with the time scale is broken whenever a graph that doesn't have time as the x-axis is placed between a time-based graph and the time scale:

![image](https://user-images.githubusercontent.com/28311615/109751156-df3ef000-7bab-11eb-8afd-55669187d274.png)

Having a unified cursor for time-based charts creates a much stronger scale/chart association: 
 
| Mouse over time-based chart | Mouse over not time-based |
|--------------------------|--------------------------|
| ![image](https://user-images.githubusercontent.com/28311615/109750924-5c1d9a00-7bab-11eb-9935-4a7eb2ba19cd.png) |  ![image](https://user-images.githubusercontent.com/28311615/109750842-2c6e9200-7bab-11eb-9622-9629d89f0f53.png) |

Prerequisite: #161

**Comment by MatthewKhouzam** [comment]
@hriday-panchasara could you link your work you already did to this issue?

**Comment by hriday-panchasara** [comment]
fixed by #675
