### ISSUE TITLE
Replace term "Analyses" with "Views" in UI?

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#292]
**Revisit this question after #157 & #286.**

The "Analyses" shown in the "Available analyses" section (ex. Histogram, Flame Chart) are Trace Compass "Views" not Trace Compass "Analyses". Replacing the term "Analyses" with "Views" in the Trace Viewer will keep language consistent with Trace Compass and reduce confusion.

| Trace Viewer Analyses | TC Analyses and Views |
|-------------------|--------------------------|
| ![image](https://user-images.githubusercontent.com/28311615/110155428-9b1e3c00-7db3-11eb-9a81-98495b996d01.png)              | ![image](https://user-images.githubusercontent.com/28311615/110156465-fef53480-7db4-11eb-8ad6-20d9b37d0f50.png) | 

## Trace Compass Analyses and Views
My understanding is that the existence of "TC Analyses" and "TC Views" comes from the implementation:
The trace data transformation path is: **Trace events --> TC Analyses --> TC Views**.
* **Analyses:** Organization or transformation of data useful for trace-based debugging. Prepared for ease of use in visualisations (or even as input to other analyses?). Often data is from trace files, but it could also be from elsewhere (ex. variable names from the program's source code). 
* **Views:** Visualization of data from one or more analyses.

### Are "TC Analyses" an important concept for a Trace Viewer user?
It doesn't seem like it. Contributors/Developers need to know whether they're writing an Analysis or a View, but the user is only interacting with Views, right?

----

CC: @ssmagula

**Comment by ebugden** [comment]
@bhufmann @MatthewKhouzam @mirsky-work What was the reason for using the term "Analyses" instead of "Views" in the Trace Viewer?

**Comment by bhufmann** [comment]
@ebugden I don't think we need to keep the Trace Compass relationship of analysis and views in the theia-trace-extension. It's not a clear cut separation anyways. In Trace Compass it's possible to provide extensions through extension points that defines analyses, and each analysis can create outputs (typically views). The Trace Compass framework then automatically shows the analysis and views according to the extension point definition. Consider the LTTng Kernel Analysis and the CPU Usage Analysis, both analyze an kernel trace but provide different views. We could argue that all the views are doing "Kernel Analysis".  Just some background.

>What was the reason for using the term "Analyses" instead of "Views" in the Trace Viewer?

To answer this questions, I'm not exactly sure why it was used initially. I guess we didn't want to have the same analysis grouping of views than in Trace Compass. The goal was to provide users a list of views (visualizations) that they can get out of a trace (or trace set). I'm ok, to change the name "Analysis" to something more meaningful.

**Comment by ebugden** [comment]
Ok so let's **leave terminology as it is now until after #157 & #286** (I'll add these as prerequisites). Once we know what we're labelling it will be easier to choose a good group label.  

> **bhufmann:** we didn't want to have the same analysis grouping of views than in Trace Compass. The goal was to provide users a list of views (visualizations) that they can get out of a trace (or trace set). I'm ok, to change the name "Analysis"

Based on your context, I think we're on the same page:
* Presenting a flat list of all available visualisations is a good place to start
* "Views" don't necessarily need to be organized based on what "Analysis" they come from like they are in Trace Compass, because this mainly communicates how they are implemented (users don't need to know this)

To keep in mind later when reviewing tool terminology:
* The term "Analysis" means something different in TC so if "Analysis" means something different in the Trace Viewer it risks confusing users/devs who have previously used TC (so most of the Trace Viewer user base?)

**Comment by ebugden** [comment]
Paraphrase of MatthewKhouzam's justification for change (from PR #297 fixing this issue)
* Views is more accurate: What is shown in the list are the dataproviders (one dataprovider per view)
* In TC, many analyses can be used to build a view (one or more analyses per view)

Direct quote:
> **MatthewKhouzam:** Analyses are an abstract concept of computation, and more importantly,
the dataproviders are shown, they have a one for one relation to views,
but a many to one relation to analyses, so views is more accurate too.

**Comment by ebugden** [comment]
At this point, I'm not sure if replacing the term "analyses" with "views" is the best decision, but testing the switch is a valid decision. We can always switch back if users are confused.
