### ISSUE TITLE
Put available views in alphabetical order

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#293]
Right now, items seem to in an arbitrary order, this makes searching for a particular list item feel longer and more confusing for users.

![image](https://user-images.githubusercontent.com/28311615/110381445-70d4b480-8027-11eb-98db-0fbdc1fa5169.png)

**Comment by MatthewKhouzam** [comment]
https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/177473 will fix it.
