### ISSUE TITLE
Make the Theia UI fully responsive

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#30]
The various Theia outputs now open at the full width of the trace viewer and with a fixed height. It should be possible to resize and move all outputs. The layout used, the react-grid-layout, should provide everything needed to do this (https://github.com/STRML/react-grid-layout)

But all the containees should also be responsive.

**Comment by justinr1234** [comment]
What’s the status of this? How can I help?

**Comment by bhufmann** [comment]
react-grid-layout is used to layout the outputs (charts) and it's possible to resize and reorder the outputs. I think we can close this issue.
