### ISSUE TITLE
Show Trace Viewer after opening via "Open Trace" button

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#315]
The Trace Viewer side panel should open automatically after opening a trace using the "Open Trace" button.

Right now it needs to be opened manually:

https://user-images.githubusercontent.com/28311615/112179788-5ecf4600-8bd1-11eb-985e-30bc1e63c32b.mp4

**Comment by muddana-satish** [comment]
I believe #308  broke this. Thanks for reporting.
