### ISSUE TITLE
Single-click a trace to set focus on tab or to open the trace

### ISSUE THREAD

**Issue by ssmagula** [theia-ide/theia-trace-extension#317]
Relates to [Issue 303](https://github.com/theia-ide/theia-trace-extension/pull/303)

If a trace's tab is already open, then a single click simply sets the focus on that tab. If the trace is not open, then a single click should open it. 

Double-clicking is unusual in a Web application, and that makes it a bit less discoverable.

**Comment by muddana-satish** [comment]
Comparing the actions to the file-explorer, I believe it makes more sense to open the trace tab on a single click. I will work on it. Thanks for reporting.

**Comment by ebugden** [comment]
This is the open action this issue refers to:

https://user-images.githubusercontent.com/28311615/117076163-f44b1300-ad03-11eb-9100-cea99af5801f.mp4

**Comment by IbrahimFradj** [comment]
I'll be working on it
