### ISSUE TITLE
Update gitpod demo for automatic server starting

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#319]
My understanding is that originally @marcdumais-work set up a script to externally start the trace server in the gitpod demo. 

@ankusht-work should this be changed now that the trace server starts automatically #298?

**Comment by marcdumais-work** [comment]
> script to externally start the trace server in the gitpod demo.

Indeed: https://github.com/theia-ide/theia-trace-extension/blob/master/.gitpod.yml#L19

> should this be changed now that the trace server starts automatically 

sounds like the thing to do.

**Comment by ebugden** [comment]
Closing since the Gitpod demo has still been working with the manually started server.
