### ISSUE TITLE
Move the timeline to its own library

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#32]
The timeline used is part of the time graph library. It should be moved in a separate library so that it can be reused (eg for XY charts) and updated separately. The timeline is the basis for navigation: zoom in/out, show the current time range.

- [ ] There is a unit controller "TimeGraphUnitController in the Time Graph library that control the "time" and a "TimeAxisComponent" that use the unit controller to draw the axis
- [ ] Maybe everything can stay in the Time Graph library or can be split into different components that can be added as dependencies
- [ ] The timeline also has a visual representation. Be creative ;-) Lttng-scope had an interesting approach

**Comment by ebugden** [comment]
Fixed by [theia-ide/timeline-chart](https://github.com/theia-ide/timeline-chart)
> **arfio:** it is in the package.json of the theia-trace-extension and is built separately so I guess the issue can be closed
