### ISSUE TITLE
Specify browsers supported for live demo

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#353]
In the [readme](https://github.com/theia-ide/theia-trace-extension#try-a-live-demo-via-gitpod), say which browsers can be used for the live demo. Alternatively, say which aren't supported? 

Someone reported that it wasn't working on Firefox. That should be confirmed.

**Comment by IbrahimFradj** [comment]
I tried the demo and tried for the browser with firefox. it works!

**Comment by ebugden** [comment]
Closing since I don't think this needs to be specified unless the demo can't work on a commonly used browser (ex. Chrome/Chromium, Firefox, Safari).  If someone reports the demo doesn't work on a popular browser and the problem won't be fixed quickly (ex. not a priority, complicated to fix), then this issue can be reopened.
