### ISSUE TITLE
Clarify trace server settings labels

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#355]
The current settings labels are vague and users are required to read the settings description to understand what it refers to. Some options for improving this: 

**Add a "Trace Server" subsection:** Having a subsection explains that the trace server is part of the trace viewer, even if it's a bit odd to only have one subsection. It also makes it possible to search for "trace server" in the settings.
![image](https://user-images.githubusercontent.com/28311615/117349723-b839be80-ae79-11eb-87d8-aed863ebf635.png)

**Change section title to "Trace Viewer Server":** No subsection, but somehow I find this more confusing that adding a subsection.
![image](https://user-images.githubusercontent.com/28311615/117350299-69405900-ae7a-11eb-8240-202041740849.png)

**More specific setting labels:** Redundancy in the labels
![image](https://user-images.githubusercontent.com/28311615/117350632-c9cf9600-ae7a-11eb-94a9-8fd0f80b3b9d.png)
![image](https://user-images.githubusercontent.com/28311615/117350685-d94edf00-ae7a-11eb-9300-b4d89f88cbad.png)

**Comment by mirsky-work** [comment]
I don't know if subsections for extensions are supported, at least I couldn't find any such example. Looking in other extensions' settings, related settings are grouped using a prefix (styled differently). For example 'Completion', 'Hover' and 'Lint' in the screenshot below. So I guess I vote for a slightly modified option 3 - 'Server: Path' and 'Server: Port'. 

![image](https://user-images.githubusercontent.com/67920463/129764894-6a4fc96b-ccc5-488c-9221-f03d3d5eabb6.png)

**Comment by ebugden** [comment]
@mirsky-work Thanks for looking into this!

**Comment by ywang001** [comment]
> I don't know if subsections for extensions are supported, at least I couldn't find any such example. Looking in other extensions' settings, related settings are grouped using a prefix (styled differently). For example 'Completion', 'Hover' and 'Lint' in the screenshot below. So I guess I vote for a slightly modified option 3 - 'Server: Path' and 'Server: Port'.
> 
> ![image](https://user-images.githubusercontent.com/67920463/129764894-6a4fc96b-ccc5-488c-9221-f03d3d5eabb6.png)

I modified it as option 3. There is colon between 'server' and 'path', and the color of 'server' and 'path' is different. If that looks good I can start a new pull request.
<img width="795" alt="Screen Shot 2021-11-01 at 4 37 00 PM" src="https://user-images.githubusercontent.com/92875879/139745438-d6189621-f38e-4184-b4ff-5c124e89e9a7.png">

**Comment by mirsky-work** [comment]
@ywang001, looks good to me, thanks!
