### ISSUE TITLE
The same trace must be opened only once 

### ISSUE THREAD

**Issue by IbrahimFradj** [theia-ide/theia-trace-extension#364]
I notice that the same trace can be opened twice. When we open the trace with TRACE VIEWER and double-click on the same open trace, another trace opens.  
Video from the gitpod demo (master):
**To reproduce (see video)**
![bug](https://user-images.githubusercontent.com/83769103/117889778-17387280-b282-11eb-9c26-fb25c23031b0.gif)

**Comment by ebugden** [comment]
Closing since description is stale (bug now produced with single click) and #450 (duplicate) has a more detailed/updated description.

**Comment by bhufmann** [comment]
I'm reopening this one because it's a different flavor of the bug that #450. #521 fixes #450 but doesn't fix it when following the steps described in this tracker.

**Comment by bhufmann** [comment]
Closing it because #521 actually fixes this issue. #569 was created to track the remaining issue.
