### ISSUE TITLE
Time Graph: Improve navigation performance

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#38]
It should be possible to navigate the time graph in a fast seamless way, no matter the size of the trace. Any performance issue observed should be improved.

**Comment by muddana-satish** [comment]
Does #153 improve the performance?

**Comment by ebugden** [comment]
⚠️**This issue is related to the Time Graph which has been moved to its own library: [theia-ide/timeline-chart](https://github.com/theia-ide/timeline-chart)**. The code related to this issue can be found in the timeline-chart library and PRs for this issue should be submitted there.

**Comment by ebugden** [comment]
Closing since Timegraph navigation performance seems reasonable at the moment. We can open a more specific issue later if we want to further improve performance.
