### ISSUE TITLE
Time Graph: Add support for arrows

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#39]
Some data providers support arrows, they should be supported by the time graph.

For arrows and annotations, look if the use of different layers for time graph would be useful.

**Comment by ebugden** [comment]
⚠️**This issue is related to the Time Graph which has been moved to its own library: [theia-ide/timeline-chart](https://github.com/theia-ide/timeline-chart)**. The code related to this issue can be found in the timeline-chart library and PRs for this issue should be submitted there.
