### ISSUE TITLE
Available Views Panel scrolls down infinitely

### ISSUE THREAD

**Issue by ghost** [theia-ide/theia-trace-extension#390]
I expect it to stop scrolling down once it reaches the last item.

![Kapture 2021-06-09 at 20 42 26](https://user-images.githubusercontent.com/70230232/121451508-53cfba80-c963-11eb-8ed3-abe6f3c3106d.gif)

**Comment by mirsky-work** [comment]
Some more information: was able to reproduce only in the browser app (on Firefox 72.0.2), but not in the Electron app.

**Comment by mirsky-work** [comment]
Wasn't able to reproduce on Gitpod running in Chrome 98.0.4758.82 or in the electron app. Closing.
