### ISSUE TITLE
Inform user when there is no data to perform analysis

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#406]
At the moment, certain views (listed below) spin infinitely when the data required for the analysis isn't in the traces. 
* This needs to happen for all chart types. Right now there is a message that displays for XY charts only #447

## To fix this
- [ ] Fix that in the fetchTree() method, the state of the component (xy-output-component.tsx) is never updated when the response indicates COMPLETED and the model is undefined.
- [ ] Update render() method to handle empty xyTree and show NO_DATA instead.
   * Ideally the message displayed would tell the user why the view is empty (ex. "Nothing to see: The data (events) required for this view are not in the trace.")

(Updated steps based on @bhufmann's [comment](https://github.com/theia-ide/theia-trace-extension/issues/406#issuecomment-874809317) below)

More context in #296 ([comment](https://github.com/theia-ide/theia-trace-extension/issues/296#issuecomment-844495341))

### Related example patches:
* [Return an empty list](https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/182636/1)
* [Display "No Data"](https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/182633) (Trace Compass patch)

## Views with this problem
* Ust memory latency vs time
* Memory usage
* Event Matching Latency - Latency vs Time

Files and function to possibly adjust:
![image](https://user-images.githubusercontent.com/28311615/124018400-cd345900-d9b5-11eb-8fb9-471495267f44.png)

**Comment by ebugden** [comment]
@bhufmann @MatthewKhouzam @tahini Could two of you review this proposed approach to make sure we're heading in the right direction?

@MatthewKhouzam Could you link the changes for the "No data" message so @jeffGonodou can use it as an example for which bits should be front end or back end? 
![image](https://user-images.githubusercontent.com/28311615/124020285-1685a800-d9b8-11eb-9b00-8e696b13f058.png)

**Comment by jeffGodonou** [comment]
Erica the name is @jeffGodonou

**Comment by MatthewKhouzam** [comment]
The patch is this one. https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/182633

**Comment by bhufmann** [comment]
@ebugden and @jeffGodonou I agree to show NO DATA message on the screen when there is a successful server response (fetchTree()) with COMPLETED status and no XY model provided by the server.  In this case the data provider in the server indicates that the analysis is completed, but no data available.

**Comment by bhufmann** [comment]
> @ebugden and @jeffGodonou I agree to show NO DATA message on the screen when there is a successful server response (fetchTree()) with COMPLETED status and no XY model provided by the server. In this case the data provider in the server indicates that the analysis is completed, but no data available.

I noticed that in the current implementation in the front-end, the XY chart shows this case the spinning wheel and "Analysis Running"  message. 
![xy-endless-spinning-wheel](https://user-images.githubusercontent.com/413424/124617037-9bebdb00-de44-11eb-8fd2-858119ba1377.gif)

This needs to be handled better in the front-end implementation for XY charts. Looking at the code in the xy-output-component.tsx, in the fetchTree() method the state of the component is never updated when the response indicates COMPLETED and the model is undefined. 

After fixing this the render() method would need to updated to handle empty xyTree and show NO_DATA instead.

**Comment by bhufmann** [comment]
> I'm on it actually. With Matthew patch added the analysis running get updated.

Which trace are you using? I have a trace that still shows the spinning wheel forever with Matthew patch. 
I think the front-end still needs to handle the case when the response status is completed and the tree model is undefined.

I'm using https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/182636/4, the apt trace in the TraceViz lab traces and open the kernel memory usage view

**Comment by jeffGodonou** [comment]
I'm using the same. Sometimes you need to reload theia.

**Comment by bhufmann** [comment]
> I'm using the same. Sometimes you need to reload Theia.

Nevertheless the front-end needs to be changed as well, to handle the condition what I described above. There might be other server implementations or data providers that return "completed" with no model.

**Comment by jeffGodonou** [comment]
I can check that

**Comment by jeffGodonou** [comment]
I notice that there were an 405 response send by the server to the theia in the case of some non functional view. I tried to make an handler of that specific response on theia without success. so I finally made an update of the state.outputState as a ResponseStatus.FAILED and handle the failure in the render method.

**Comment by jeffGodonou** [comment]
![image](https://user-images.githubusercontent.com/25375286/126177637-35b55cd4-2ff6-4781-afcb-fb85dadf5670.png)

**Comment by jeffGodonou** [comment]
Do you think it would have been a good idea to send a different response from the server knowing that the 405 response is referenced as a method not allowed?

**Comment by jeffGodonou** [comment]
> I notice that there were an 405 response send by the server to the theia in the case of some non functional view. I tried to make an handler of that specific response on theia without success. so I finally made an update of the state.outputState as a ResponseStatus.FAILED and handle the failure in the render method.

Solved

**Comment by ebugden** [comment]
@ssmagula and I suggest displaying this message instead of "No data":

Trace analysis complete.
No related events found.

(We want to tell the user: We completed the operation you requested successfully, but we didn't find anything useful.)

**Comment by ebugden** [comment]
The PR that is set to close this issue only applies to XY charts. @bhufmann Could any timeline chart views run into the issue of not having the events required to perform an analysis? Is there a way to manage this for all chart types instead of adding the same code to each output component?

**Comment by ebugden** [comment]
Reopening since PR #447 only covers XY charts (see [comment](https://github.com/theia-ide/theia-trace-extension/issues/406#issuecomment-932291732) above). Want to confirm this isn't also an issue for timeline charts or other chart types.

**Comment by bhufmann** [comment]
> The PR that is set to close this issue only applies to XY charts. @bhufmann Could any timeline chart views run into the issue of not having the events required to perform an analysis? If this is also a risk for timeline charts, is there a way to manage this for all chart types instead of adding the same code to each output component?

@ebugden Yes, it's true. Any view could potentially run in the same situation.
