### ISSUE TITLE
Connection to trace server fails in gitpod demo

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#415]
Server starts successfully (in the gitpod demo [the server is started manually in the gitpod.yml script](https://github.com/theia-ide/theia-trace-extension/blob/69c60215223f23b70c275a8ad65504697f44b21a/.gitpod.yml#L19)), but when opening a trace, the front end appears to fail to connect to the trace server. (The front end tries to automatically restart the server and fails with "Error opening serial port 8080 (Port busy)" since there's already a server running on that port.)

More context courtesy of @arfio: 
* Dev console shows: "has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."
* Others experiencing the same issue recently: [CORS errors due to new Gitpod port policy?](https://community.gitpod.io/t/cors-errors-due-to-new-gitpod-port-policy/4042)

https://user-images.githubusercontent.com/28311615/125679569-b3e002cd-365d-4891-8897-f2540cc6bf7e.mp4

## Hypothesis 1 - Externally started server is confusing the front end (incorrect)
Stopped the manually started server and allowed the front end to start the server. Initially, this appears to work (trace file explorer comes up), but when a trace is opened it seems to lose connection to the server and tries to restart it (but fails because there's already a server running).

https://user-images.githubusercontent.com/28311615/125683099-5c545102-c020-4c5b-94c9-c49558bc40ac.mp4

## Hypothesis 2 - Gitpod is using port 8080 in some way and this is causing issues (incorrect)
Changed the port in the Trace Viewer settings and tried to open traces. Got the same behaviour as the previous hypothesis (file explorer comes up, but when try to open trace it breaks) and restart server, but always receives the same port busy error.

https://user-images.githubusercontent.com/28311615/125683734-1cea9a74-a470-4350-b9d2-9d5ede3424b6.mp4

## Unverified hypotheses
* Server hasn't started completely when the trace files are opened and so it thinks no server is running and tries to restart it

**Comment by arfio** [comment]
Gitpod configuration was changed with this pull request: https://github.com/gitpod-io/gitpod/pull/4548
This breaks the connection between the trace-compass server and the theia-trace-extension frontend. Changing the port visibility to public makes the gitpod demo work again. https://www.gitpod.io/docs/config-ports#configure-port-visibility

Also it is possible to test it quickly if you click on the lock in the list of ports in Gitpod. This makes the port public without having to modify the configuration.

**Comment by ebugden** [comment]
I confirm that manually changing the service on 8080 to public makes things work again! Thanks @arfio! 

With private 8080 and then public 8080: 

https://user-images.githubusercontent.com/28311615/125689970-fb35967e-fb06-4b2f-b039-4cacfe897c26.mp4
