### ISSUE TITLE
XY Chart: Add y-axis

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#421]

**Comment by Rodrigoplp-work** [comment]
Other charts, like the Resource Status, do not have a y axis, but still need to be vertically aligned with all other charts. This creates an empty space that we can leave empty or use in some other way.
I put together 3 options for using this space:

- Option A: y-axis outside xy chart, other charts stay as they are.

<img width="743" alt="Option A" src="https://user-images.githubusercontent.com/88502808/142059230-376c79d0-3762-4d7d-b7f1-5a5c8c9e07dd.png">  

- Option B: y-axis inside xy chart, other charts and top x axis show blue empty space.

<img width="696" alt="Option B" src="https://user-images.githubusercontent.com/88502808/142059314-1f6413a4-e03e-4bd0-bf34-790e82aa3ed9.png">  

- Option C: y-axis inside xy chart, other charts have the extra space on the left filled by the tree (text). Top x axis is indented.

<img width="742" alt="Option C" src="https://user-images.githubusercontent.com/88502808/142059386-4dc960bd-e008-4260-a78d-786c231a0482.png">

**Comment by MatthewKhouzam** [comment]
I will give another example of how it could be done: 
![image](https://user-images.githubusercontent.com/419535/142070760-2f9d459f-0f9e-41b3-b9ff-9b0c70bb255a.png)

From 
https://github.com/d3/d3-axis

I am thinking that it could be interesting with a couple of base assumptions.

1. Users read the center of the view more than the sides
2. Zooming is a more common action than panning.

However, the only way to be sure is to try it out some more.

**Comment by ebugden** [comment]
@Rodrigoplp-work Thanks for taking the time to post design options in advance! I like the option you went with in the PR #567.
