### ISSUE TITLE
Release to npm

### ISSUE THREAD

**Issue by JonasHelming** [theia-ide/theia-trace-extension#429]
First of all, thank you for contributing this great extension!!!

Do you have plans to publish it to npm? This would make consuming it much easier...

**Comment by JonasHelming** [comment]
@MatthewKhouzam

**Comment by bhufmann** [comment]
Thanks for the interest in this project.

Yes, we plan to publish the work to npm to make the consumption easier.  We haven't got to it since we focused on progressing with features and improvements. The current plan is to have it available by end of Q3. 

Do you have any indication when you would need the NPM packages? Please let me know.

**Comment by JonasHelming** [comment]
Thank you for the answer! We do not really have a deadline, but it is the classic "asap".
We are currently evaluating the trace extension in a custom product. At the moment, this requires some over head for the integration, which would be much simpler with an npm package. When you develop the extension further, there would be even continuous over head in updating (without npm). So if you ask me, I would first publish an alpha version that you can update over time with improvements, especially, if you plan this anyways. This would make it much easier for potential adopters to evaluate your great project.
This is only my point of view, we are actually thankful and very happy about your great contribution to the ecosystem!

**Comment by JonasHelming** [comment]
Could you give me an update on when the NPM push is planned, so we can allign our adoption planing? @MatthewKhouzam

**Comment by bhufmann** [comment]
Here are the links:

https://www.npmjs.com/package/theia-traceviewer
https://www.npmjs.com/package/traceviewer-react-components
https://www.npmjs.com/package/traceviewer-base

**Comment by JonasHelming** [comment]
Thank you for providing this!
