### ISSUE TITLE
Time Graph: Align row labels with rows (recent Chrome only)

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#433]
On recent Chrome browsers, there is a large vertical offset between where the chart starts and where line labels start so labels do not line up with the associated rows. (Row information is still available using the tooltip, but this isn't convenient)

* Observed in both Resources Status and Thread Status views, so bug assumed present in all timegraph views.
* Browser: Chrome, Version 92.0.4515.107

> **bhufmann:** This problem only started with recent Chrome versions. Older Chrome versions or Firefox (v90.0) don't have that issue. I don't know which version it started, but with Chrome version 92.0.4515.107 it fails.

https://user-images.githubusercontent.com/28311615/127364700-05f6899b-fbe7-43cc-a4df-f8d43a9cd7ff.mp4

**Comment by ebugden** [comment]
Let me know if this is too specific to the timeline chart and should be moved to the [timeline-chart repo issues](https://github.com/theia-ide/timeline-chart/issues).

**Comment by bhufmann** [comment]
> Let me know if this is too specific to the timeline chart and should be moved to the [timeline-chart repo issues](https://github.com/theia-ide/timeline-chart/issues).

I think that the problem needs to be fixed here because the tree implementation and row synchronization is in the theia-trace-extension. So, let's keep the tracker here.

**Comment by bhufmann** [comment]
@ebugden This problem only started with recent Chrome versions. Older Chrome versions or Firefox (v90.0) don't have that issue. I don't know which version it started, but with Chrome version 92.0.4515.107 it fails.

**Comment by ebugden** [comment]
Ok, thanks for the context! I'll add it in the issue description.
