### ISSUE TITLE
Reduce contrast of grid lines

### ISSUE THREAD

**Issue by ssmagula** [theia-ide/theia-trace-extension#441]
Grid lines are much more common yet much less important than the data being visualized, and therefore grid lines should be about "one noticeable difference" in contrast from the background of the chart. The current chart background is #232323. I'm proposing we use these colors for horizontal and vertical grid lines:

- #35373B for horizontal grid lines
- #2B2E31 for vertical grid lines

This will yield a more subdued grid similar to this screenshot (click to view something closer to actual pixels):
![image](https://user-images.githubusercontent.com/1106582/128368980-4d57fa3b-8145-495a-af69-240bdf33b52e.png)

Let's compare and contrast (pun intended!) that grid with this grid in the current implementation:
![image](https://user-images.githubusercontent.com/1106582/128369614-54b86b72-3cb4-49c8-bc53-2c7a8e1f07b9.png)

In the above example, the grid lines are much, _much_ more prominent than the data itself. 

Because the proposed grid lines are more subdued, in a future iteration we may want to supplement the grid by highlighting grid lines when the user mouses near a line or an intersection of lines. In the current iteration the user must click.

**Comment by MatthewKhouzam** [comment]
Thanks, I think this can be tackled in the short term.

**Comment by ebugden** [comment]
**Prerequisite:** #282 (Merging PR #382)
