### ISSUE TITLE
The relationship between the table event and the xy charts are not linked

### ISSUE THREAD

**Issue by IbrahimFradj** [theia-ide/theia-trace-extension#448]
When I select events in the events table, I don't see the selection range in the xy charts.

**The issue (with xy chart) :**

![ bug table event1](https://user-images.githubusercontent.com/83769103/129410366-0c652adc-3165-4cce-be4b-ad8cb4badfcb.gif)

**The expected result (with timegraphe chart) :**

![ expected table event1](https://user-images.githubusercontent.com/83769103/129410337-65c4d143-b3fe-42c6-ad2e-43715c0ada56.gif)

**Comment by ebugden** [comment]
Some more details!

## Timeline chart + XY Charts + Events Table
If there is a Gantt chart open, the XY charts will respond to selections made in the Events Table.

https://user-images.githubusercontent.com/28311615/144064695-e9eedf21-2415-4d01-9148-11b0b653f0ef.mp4

## Just XY charts + Events Table
If only XY charts are open the XY charts to not respond to selections made in the Events Table (also shown in the issue description):

https://user-images.githubusercontent.com/28311615/144064238-40f03636-59b6-4a4f-8da9-eb10163cc1b9.mp4

Events Table responds to selection in the XY charts (event selected in the XY chart it highlighted in the events table)

https://user-images.githubusercontent.com/28311615/144064773-0ee76a1e-5656-47b8-addd-eca900558bf8.mp4
