### ISSUE TITLE
Reduce time graph cached data

### ISSUE THREAD

**Issue by PatrickTasse** [theia-ide/theia-trace-extension#469]
Currently, when the timeline chart requests the application to fetch time graph data for a certain 'range' and 'resolution', the application fetches 5x the requested range (2x range cache on each side) and this data is fetched with 25% more resolution.

This allows the fetched model to be cached and allow the user to navigate within a certain threshold before new data needs to be fetched. As long as the user doesn't pan away for twice the original range on either side, or zoom in more than 25% from the original zoom level, then the model is not updated.

The downside is that the fetched model represents 5x * 1.25x = 6.25x more data than required for the current window. Also, when zooming in slightly (less than 25%) the model does not get updated.

This increases the processing delay when fetching row data and the network utilization for these messages, for data that may not be needed depending on the user's navigation pattern.

It should be considered whether a smaller cache width could be fetched. For the resolution, a throttling mechanism could be used, where the new data model is fetched only when user stops navigating, after a short delay.

**Comment by bhufmann** [comment]
@PatrickTasse the cache requested by the timeline-chart library or is it handled in the theia-trace-extension.

**Comment by PatrickTasse** [comment]
The cache is added in theia-trace-extension, see TimeGraphOutputComponent.fetchTimegraphData().

**Comment by PatrickTasse** [comment]
Fixed with https://github.com/theia-ide/theia-trace-extension/pull/516
