### ISSUE TITLE
Trace Explorer: Sort outputs alphabetically

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#49]
Outputs are now sorted arbitrarily, such that 2 traces having the same outputs or at least many common ones, will show the outputs differently sorted.

They should be sorted in a consistent way, such that if output X if before output Y for one trace, it is always so for other traces.

**Comment by bhufmann** [comment]
Trace Compass server providing a list of outputs in alphabetical order:
https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/177473
