### ISSUE TITLE
Trace Viewer: Allow navigation with mouse and keyboard

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#51]
It should be possible to navigate a trace using either the keyboard or mouse, like in Trace Compass:

- WASD: WS to zoom, AD to pan
- Arrows: navigate at the same zoom level in the direction
- Mouse: scroll: zoom in/out

**Comment by ankusht-work** [comment]
@tahini : Could you please verify if this pull request in the "time-line chart" addresses the requirements you have listed above?.  https://github.com/theia-ide/timeline-chart/pull/25
Thanks.!!

**Comment by tahini** [comment]
This issue is solved here. Some smaller more fine-grained issues have been opened in the https://github.com/theia-ide/timeline-chart repo
