### ISSUE TITLE
Hide zoom toolbar icons when time related chart is not opened.

### ISSUE THREAD

**Issue by ghost** [theia-ide/theia-trace-extension#527]
Icons show even when there is no chart opened.

![image](https://user-images.githubusercontent.com/70230232/137930846-07b6d78d-05b2-47c2-a1f8-2d7b831b65fe.png)

**Comment by ssmagula** [comment]
Maybe it would be better to display a disabled state for any inactive tools? Possible benefits: 
- When elements disappear, new users might wonder "where'd it go? Why it'd disappear?"
- It's good for the "chrome" of the UI (the stuff that's always visible) to be  very predictable or stable in position (changes can distract/call attention)
- Disabled elements can have a tooltip that helps user grasp "why"
