### ISSUE TITLE
Opening of LTTng trace fails when running theia-traceviewer and server on Windows

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/theia-trace-extension#545]
When opening a LTTng kernel trace (e.g. using Open With -> Trace Viewer) on Windows using the Trace Compass server in Windows fails with error:  "Invalid trace(s): kernel"

To reproduce use Theia Blueprint for C https://download.eclipse.org/theia/c/1.17.2/windows/TheiaBlueprintForC.exe and Trace Compass server nightly build for windows: https://download.eclipse.org/tracecompass.incubator/trace-server/rcp/

**Comment by arfio** [comment]
This issue is documented on the Theia IDE github: https://github.com/eclipse-theia/theia/issues/8098.

**Comment by bhufmann** [comment]
Workaround and additional required fix are implemented in the trace server. See trace server [Bug 577145](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577145) and [Patch](https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/187548) for that.

**Comment by bhufmann** [comment]
The trace compass server has been updated and a new server build is available: https://download.eclipse.org/tracecompass.incubator/trace-server/rcp/

I tested it with `Theia Blueprint for C` and it works now.

**Comment by bhufmann** [comment]
Opening it in Windows fails again. Changes in #554 make the Theia bug (https://github.com/eclipse-theia/theia/issues/8098) visible again. It fails now during the execution of the theia-traceviewer code and the following error is shown:
![image](https://user-images.githubusercontent.com/413424/153051027-743f18f2-0a51-4722-ae89-fcbc3752ffa4.png)

**Comment by hoangphamEclipse** [comment]
A patch for a work around is available for review. Please see PR [674](https://github.com/theia-ide/theia-trace-extension/pull/674).

**Comment by bhufmann** [comment]
Fixed by #674
