### ISSUE TITLE
Check if you can upload typical traces to Gitpod

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#566]
Test if it is possible to upload a typically sized trace file (ex. 1G) to Gitpod within a reasonable delay (ex. 30 s to 1 min). 

The main reason to have a downloadable pre-packaged version of the Trace Viewer #352 is so that prospective users can try analyzing their own traces. Apparently, the [downloadable application](https://github.com/theia-ide/theia-trace-extension#download-an-external-build-of-the-application) is currently broken #560, but if it's possible to upload typical traces then fixing it isn't as critical.

## To test
In Gitpod you can upload files/folders in a couple ways:
* Recommended: You can drag and drop folders into gitpod to upload them
* With the UI (right-click → Upload files) you can upload files, but not folders. You’d have to compress the folder, upload the archive, then decompress it using the Theia terminal

**Comment by ebugden** [comment]
@yoann-heitz Could you check this?

**Comment by yoann-heitz** [comment]
@ebugden I tested both methods.
My uncompressed trace weight was 990MB, 133MB when compressed. My upload speed was around 29MB/s

Drag and drop method : 9min30s to upload the uncompressed trace
Upload files menu method : 1min15s to upload the compressed trace

Also, you can upload several files at once with the Upload files menu (Left Ctrl + click on every file or keep click pressed down) but you have to create an empty directory and select it first on Theia to have all the trace files in the same directory

**Comment by ebugden** [comment]
> Drag and drop method : 9min30s to upload the uncompressed trace
Upload files menu method : **1min15s to upload the compressed trace**

Ok yeah I think that would feel too long for users. 
* Having to compress your trace before is also a bit of a pain. 
* Not to mention that many users wouldn't feel comfortable uploading their traces publicly. 

So we do have to figure out what's up with the downloadable application! #560 

Thank you @yoann-heitz for looking into this!
