### ISSUE TITLE
Empty legend column in XY Charts

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/theia-trace-extension#579]
Each xy-chart has a legend column as last column in the tree which is currently not populated. This was done to mimic the way it was done in Eclipse Trace Compass. 

![image](https://user-images.githubusercontent.com/413424/143314576-d70ed750-dd99-451a-823e-0af366625d6f.png)

The column should be removed from the view because it doesn't contain any data.

**Comment by ebugden** [comment]
Is this planned for before the end of December? (If not, I'll move it to the "post-MVP" milestone)

**Comment by bhufmann** [comment]
Yes, the removal should be done for the MVP.

**Comment by ebugden** [comment]
Nice! That was fast
