### ISSUE TITLE
Manage session and server connectivity

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#58]
If while the user navigates on the theia-trace-extension, either the trace server or the theia backend is shut down, the UI should handle the absence of server correctly and reconnect when it is coming back

**Comment by ebugden** [comment]
I think the front end does this now. @ankusht-work could you confirm?

**Comment by mirsky-work** [comment]
@ebugden I tested it and looks like the BE reconnects automatically when the server comes back online, but there's no visual indication when the server goes offline.

**Comment by ebugden** [comment]
> **mirsky-work:** @ebugden I tested it and looks like the BE reconnects automatically when the server comes back online, but there's no visual indication when the server goes offline.

I think we could create a separate issue for adding a message when the server is offline. Or use #321 as a reminder to do this. I would close this issue.

Did #298 add these features?
