### ISSUE TITLE
Memory Usage (UST) view spins infinitely

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#619]
The Linux UST memory usage view behaves incorrectly: 
* It shows "Analysis running" forever. This is probably because the analysis fails in a way that is not handled yet so the view state is not updated.
* The view only pops into existence in the tool once a second view is selected. It can't be the first analysis selected.

Possible solutions:
* Filter the view until it works
* Make sure state is updated so that the "Analysis failed" message displays 

https://user-images.githubusercontent.com/28311615/149542994-e2688391-05ea-480c-89e7-3b8ccb43674c.mp4

**Comment by ebugden** [comment]
Looking into this and will take notes here:
* The UST Memory Usage view gets added to the list of outputDescriptors (the list of views displayed) and then crashes somewhere afterwards, but it stays in the list of outputDescriptors

**Comment by bhufmann** [comment]
Thanks for reporting this. I did some investigation and then I noticed that the data provider ID is incorrect for the UST Memory Usage view. This needs to be fixed in the trace server back-end. I opened [Bug 578267](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578267) and submitted a fix for review.

**Comment by bhufmann** [comment]
The bug in the Trace Compass server is fixed and a new server build is available [here](https://download.eclipse.org/tracecompass.incubator/trace-server/rcp/). I verified with Gitpod that the bug is resolved.

**Comment by ebugden** [comment]
@bhufmann Thank you for resolving this!
