### ISSUE TITLE
Instructional video: scatter plots

### ISSUE THREAD

**Issue by Rodrigoplp-work** [theia-ide/theia-trace-extension#665]
Create an instructional video 2 minutes long or so, about the new scatter plots and its tooltips.

**Comment by Rodrigoplp-work** [comment]
### Video title

Scatter plots on Theia Trace Extension

### Video description

Theia Trace Extension now can plot scatter data. Let's see how to access this new type of analysis, and the best ways to retrieve information from it.

### Script

We are bringing scatter plots to Theia Trace Extension. Let's take a look at how to use them.

When you open a trace like this one and you look at your analysis, the scatter plots will appear on the ones that have "latency vs. time" in the title.

Let's use this one, for example.

Unlike the time series, where you have one data point per pixel along the chart, with scatter plots the data is dispersed.

To get detailed information out of your data, you can use the tooltip. Move your mouse close to a point and stop for a second. You will see the name of the process, its time stamp and its value.

In case you have more than one process on the chart, the tooltip will display information about the closest point of each one of the processes.

That is true even if there are too many points clustered together.

In this case, you will see the data of one point, the closest one, of each nearby series.

[Pause]

The tooltip is designed to be responsive and fast, even with large data sets. Like here, if we select all processes, the tooltip still appears as fast as when we had just a few points on screen.

The tooltip also allows interaction. Move the mouse inside it, and you will be allowed to select text, which you can copy if so desired.

**Comment by Rodrigoplp-work** [comment]
https://user-images.githubusercontent.com/88502808/151878335-591335bc-7bd4-425d-bbb6-0701603f33f6.mp4

**Comment by MatthewKhouzam** [comment]
Hi, it's great work, I suggest lowering the volume a bit as it crackles. It gets MUCH better 0:55s

**Comment by MatthewKhouzam** [comment]
The end is too quick, we need an intro and a conclusion.

**Comment by MatthewKhouzam** [comment]
Something like

intro:
Hello, I will describe the scatter plot feature in the Theia Trace Extension, the web based front-end for Trace Compass.

<body>

</body>
To recap, this tool is used often for showing discrete values on a plot. In this example, we've seen latencies, but this is just another tool that can fit into your forensic belt while troubleshooting an issue. Stay tuned for more features.

**Comment by Rodrigoplp-work** [comment]
https://user-images.githubusercontent.com/88502808/151884537-84a42a32-6f74-4d94-9659-708fad020d23.mp4

**Comment by Rodrigoplp-work** [comment]
Here is a version with -20dB preset on the microphone. I think it resulted in a better audio track.

https://user-images.githubusercontent.com/88502808/151999456-068d9bac-ed20-4d2c-a52c-abd3476b8042.mp4

**Comment by Rodrigoplp-work** [comment]
This is the version with Audacity filters (compression and noise reduction over -20 dB recording):

https://user-images.githubusercontent.com/88502808/152047000-8473542f-3bde-48bf-a18a-458b17fd6d46.mp4

**Comment by MatthewKhouzam** [comment]
https://youtu.be/di8PP-OtB5E <-- merged!
