### ISSUE TITLE
Instructional video: synchronisation between tools

### ISSUE THREAD

**Issue by Rodrigoplp-work** [theia-ide/theia-trace-extension#666]
Create an instructional video 2 minutes long or so, about how Theia Trace Extension views work in sync.

**Comment by Rodrigoplp-work** [comment]
### Video title

Synchronous analysis

### Video description

Analysis tools in Theia Trace Extension work in sync, which is a powerful way to extract information from your data. Here is one way of making use of this feature.

### Script

Hello. I will talk about synchronization in Theia Trace Extension, the web based front-end for Trace Compass.

Analysis tools in Theia Trace Extension work in sync, which is a powerful way to extract information from your data. To see how that works, let's start by selecting a trace, then opening a few views.

Here we have a time line analysis in the CPU usage view, a time graph in Resource Status, and an Events Table.

Clicking on any point in the CPU Usage chart, for example, brings up a marker in the same point of the Resource Status chart, and highlights the corresponding line in the Events Table.

Conversely, selecting a row in the table brings up the marker of that data point in the opened charts.

All selections work the same way. So, selecting several rows in the table makes a shaded area corresponding to the selection appear in the charts.

Just like selecting an area in the charts highlights the respective rows in the table.

So this shows that the analysis tools we have in Theia Trace Extension, when used together, allow for extra insights and a more comprehensive understanding of your data.

Stay tuned for more features.

**Comment by MatthewKhouzam** [comment]
Looks great! please be mindful of the audio levels while recording videos. ;) Try to keep them in "green"

**Comment by Rodrigoplp-work** [comment]
I decreased them to 75%, but if it's still high I can try to get creative with a few filters.
No worries about re-recording it, I put the audio on a separate track.

**Comment by Rodrigoplp-work** [comment]
https://user-images.githubusercontent.com/88502808/151887027-71db024a-22f3-4ef8-80bb-4be7e7e1c115.mp4

**Comment by MatthewKhouzam** [comment]
Are you using audacity, if so, please run a denoise filter on the sound. You need to select the first second for a noise profile, then it removes that sound from the full video. I can show you.

**Comment by Rodrigoplp-work** [comment]
I actually recorded a second run setting a -20dB filter directly on the microphone. I believe this is a lot better. Let me know. If not, I'll try the denoise filter you mentioned.

https://user-images.githubusercontent.com/88502808/152002667-190750b0-e816-4891-826f-5e7b0124efe6.mp4

**Comment by Rodrigoplp-work** [comment]
Version with Audacity filters (compression and noise reduction over -20 dB recording):

https://user-images.githubusercontent.com/88502808/152050258-64f6671b-9d48-451e-b78e-2508c441dd94.mp4

**Comment by MatthewKhouzam** [comment]
Merged!
