### ISSUE TITLE
Recover from a restarted trace server without refreshing the page

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#71]
If the trace server went offline and goes back up, refreshing the page sends the traces back to the server and allows to continue navigating. It should be possible to recover automatically, by detecting if a trace/experiment does not exist anymore on the server and sending it back.

**Comment by ebugden** [comment]
@mirsky-work Can this be closed? Does the automatic trace server management handle this?

**Comment by mirsky-work** [comment]
> @mirsky-work Can this be closed? Does the automatic trace server management #298 handle this?

Yes, I tested on Gitpd and this one can be closed. I'm not sure which PR addressed it though.
