### ISSUE TITLE
Steamline trace selection from trace explorer and other locations

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#73]
When a trace/experiment is opened, a new tab is opened for it and the trace appears in the Trace Explorer under the Opened Experiment.

- [ ] When a user selects a trace under the Opened Experiement, its tab should be opened. 

- [ ] When a user selects a tab, the corresponding trace should be selected under the Opened Experiments and also the root path of the experiment should be selected in the File explorer, like it would for a source code file

- [ ] Sometimes, an experiment may be available under the Opened Experiments, but no corresponding tab is opened, for instance, if the trace was opened in another browser, or from another workspace. Here one of 2 things should be done: 

1. detect that no tab is opened for this trace and do not display the trace (in which case, it will not be possible to delete this trace from the trace server), or maybe just for traces that are not on this workspace?

2. Open a tab for it.

**Comment by ebugden** [comment]
Fixed by PRs #180, #318 (and others?)

Except for "the root path of the experiment should be selected in the File explorer, like it would for a source code file" because opened traces aren't necessarily in the workspace.
