### ISSUE TITLE
Support themes in the theia-trace-extension and it's graphs 

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/theia-trace-extension#76]
Theia supports changing the theme, however, the theia-trace-extension doesn't apply it. The current implementation only supports the dark them. When switching to a light theme, the background of all the different graph types is still black.

**Comment by mad-season** [comment]
@bhufmann Can we plan on supporting 1 light theme and the current dark theme? At least for the MVP?

I can take a stab at this one...

**Comment by bhufmann** [comment]
> @bhufmann Can we plan on supporting 1 light theme and the current dark theme? At least for the MVP?
> 
> I can take a stab at this one...

Yes, I think too, we should support at least one light theme and one dark theme for the MVP. 

It currently doesn't give the best impression for the user when using for example the Theia light theme.

![image](https://user-images.githubusercontent.com/413424/98257752-0bc06380-1f4e-11eb-9f57-d5a41d55fb46.png)

**Comment by ebugden** [comment]
From a UX perspective, we're hesitant to support all themes in the plugin:
* Colour has an important functional role in complex visualisations and it would be impossible to guarantee that the visuals play nicely with all themes. 
* Colour consistency/determinism across users allows the brain to develop colour association reflexes which are much faster than consciously identifying elements.

At the moment, I'm imagining leaning towards just a light and a dark theme in the plugin. Having just two colour themes would sacrifice a sense of visual integration for those who have other themes and add visual noise, but I think we can get a sense of how many people find that annoying during user tests and mitigate it later.

**Comment by bhufmann** [comment]
@ebugden I agree, initially for the MVP it's ok to support dark and light themes. Please note that colors for the graphs (states, lines) are proposed by the trace server back-end. For the known graphs in the MVP these colors are fine for light and dark them. 

Later on, we need to think about the theming in a more broader sense. What I mean we probably need to adjust the graph colors in the front-end depending on the theme (i.e. to avoid something like blue on blue background or bad color contrast). This is not in scope for the MVP and this initial theme support.
