### ISSUE TITLE
Allow to configure the URL of the trace server

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#79]
This will allow the gitpod CI to connect to the server started by gitpod

**Comment by tahini** [comment]
Some extra information about gitpod: on the container, gp url will give the url of the gitpod container, so the trace server URL can be obtained by adding the port number in from the url as follows:

```
$ gp url
https://someuuid.ws-us02.gitpod.io
```
URL of the trace server would be http://8080-someuuid.ws-us02.gitpod.io

We could then send it on the command line

**Comment by marcdumais-work** [comment]
> ```
> $ gp url
> https://someuuid.ws-us02.gitpod.io
> ```
> 
> URL of the trace server would be http://8080-someuuid.ws-us02.gitpod.io
> 

IIRC they have like 3 "computing centers", so that wherever you are, one will be probably within 50ms ping time, which works very well for `browser` Theia apps. The URL above is the US center. Expect minor variations for the others. From memory: Europe and maybe Asia?
