### ISSUE TITLE
Trace Explorer view not part of left-side panel by default

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-trace-extension#80]
I think it should be added. I see two possibilities about where to do this:

- 1- In the extension in this repo. This means that by adding this extension to a Theia application will automatically add the Trace explorer to the panel. 
- 2- Do this as a customisation to the example application. Then it would only affect that application, but could serve as example for others that want to do same

**Comment by marcdumais-work** [comment]
@vince-fugnitto maybe something you could consider contributing, once we have an agreement on what to do.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto maybe something you could consider contributing, once we have an agreement on what to do.

Sure, that sounds good :)

**Comment by tahini** [comment]
I think option 1 should be considered. If someone installs this extension, she's probably interested to see traces eventually, so it makes sense to have the Trace explorer show automatically (or when a trace is opened? is that possible to open a view in the panel given some action?), especially that there is no other way to "discover" the tracing feature without this view.

**Comment by marcdumais-work** [comment]
> I think option 1 should be considered. If someone installs this extension, she's probably interested to see traces eventually, so it makes sense to have the Trace explorer show automatically (or when a trace is opened? is that possible to open a view in the panel given some action?), especially that there is no other way to "discover" the tracing feature without this view.

Sounds good. I was just thinking that this way of doing things may not scale if all extensions were to do the same (think e.g. of crowded menus in classic Eclipse apps, when many plugins are installed). OTOH I think we can have a "higher level" solution at some point, to allow IDE developers to chose what's present/opened by default, no matter what an extension says. A bit like classic Eclipse perspectives.

**Comment by vince-fugnitto** [comment]
> > I think option 1 should be considered. If someone installs this extension, she's probably interested to see traces eventually, so it makes sense to have the Trace explorer show automatically (or when a trace is opened? is that possible to open a view in the panel given some action?), especially that there is no other way to "discover" the tracing feature without this view.
> 
> Sounds good. I was just thinking that this way of doing things may not scale if all extensions were to do the same...

@marcdumais-work just as an FYI, we can support the same feature like in vscode which allows end-users to choose what they want to be displayed by default (check for default views):

![peek-a-boo](https://user-images.githubusercontent.com/40359487/85037641-9fd28f80-b153-11ea-8d8d-6aa5a7835f29.gif)

**Comment by marcdumais-work** [comment]
> just as an FYI, we can support the same feature like in vscode which allows end-users to choose what they want to be displayed by default (check for default views):

Cool. Something like that could be used by end-users to customise what's provided by the IDE app designer.
